version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:6-alpine
    restart: always
    expose:
      - 6379

  worker:
    image: registry.app.co.id/vms/be/worker:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - "./public:/app/public"
      - "./credential:/app/credential"
    env_file:
      - .env

  websocket:
    image: registry.app.co.id/vms/be/websocket:latest
    ports:
      - 8081:8081
    depends_on:
      - postgres
      - redis
      - worker
    volumes:
      - "./public:/app/public"
      - "./credential:/app/credential"
    env_file:
      - .env

  api:
    image: registry.app.co.id/vms/be/api:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
      - worker
    volumes:
      - "./public:/app/public"
      - "./credential:/app/credential"
    env_file:
      - .env

  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
